/* Automatically generated by chibi-ffi; version: 0.2 */

#include <chibi/eval.h>

#include "port.c"

static sexp sexp_peek_u8_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2) {
  sexp res;
  res = sexp_peek_u8(ctx, self, arg2);
  return res;
}

static sexp sexp_read_u8_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2) {
  sexp res;
  res = sexp_read_u8(ctx, self, arg2);
  return res;
}

static sexp sexp_write_u8_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2, sexp arg3) {
  sexp res;
  res = sexp_write_u8(ctx, self, arg2, arg3);
  return res;
}

static sexp sexp_utf8_3E_string_x_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2) {
  sexp res;
  res = sexp_utf8_to_string_x(ctx, self, arg2);
  return res;
}

static sexp sexp_25_string_3E_utf8_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2) {
  sexp res;
  res = sexp_string_to_utf8(ctx, self, arg2);
  return res;
}

static sexp sexp_string_count_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2, sexp arg3, sexp arg4, sexp arg5) {
  sexp res;
  res = sexp_string_count(ctx, self, arg2, arg3, arg4, arg5);
  return res;
}

static sexp sexp_get_output_bytevector_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2) {
  sexp res;
  res = sexp_get_output_bytevector(ctx, self, arg2);
  return res;
}

static sexp sexp_open_output_bytevector_stub (sexp ctx, sexp self, sexp_sint_t n) {
  sexp res;
  res = sexp_open_output_bytevector(ctx, self);
  return res;
}

static sexp sexp_open_input_bytevector_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2) {
  sexp res;
  res = sexp_open_input_bytevector(ctx, self, arg2);
  return res;
}

static sexp sexp_25_make_custom_output_port_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2, sexp arg3, sexp arg4) {
  sexp res;
  res = sexp_make_custom_output_port(ctx, self, arg2, arg3, arg4);
  return res;
}

static sexp sexp_25_make_custom_input_port_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg2, sexp arg3, sexp arg4) {
  sexp res;
  res = sexp_make_custom_input_port(ctx, self, arg2, arg3, arg4);
  return res;
}

static sexp sexp_set_file_position_x_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0, sexp arg1, sexp arg2) {
  sexp res;
  if (! sexp_portp(arg0))
    return sexp_type_exception(ctx, self, SEXP_IPORT, arg0);
  if (! sexp_exact_integerp(arg1))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg1);
  if (! sexp_exact_integerp(arg2))
    return sexp_type_exception(ctx, self, SEXP_FIXNUM, arg2);
  if (!sexp_stream_portp(arg0))
    return sexp_xtype_exception(ctx, self, "not a FILE* backed port", arg0);
  res = sexp_make_integer(ctx, fseek(sexp_port_stream(arg0), sexp_sint_value(arg1), sexp_sint_value(arg2)));
  return res;
}

static sexp sexp_file_position_stub (sexp ctx, sexp self, sexp_sint_t n, sexp arg0) {
  sexp res;
  if (! sexp_portp(arg0))
    return sexp_type_exception(ctx, self, SEXP_IPORT, arg0);
  if (!sexp_stream_portp(arg0))
    return sexp_xtype_exception(ctx, self, "not a FILE* backed port", arg0);
  res = sexp_make_integer(ctx, ftell(sexp_port_stream(arg0)));
  return res;
}


sexp sexp_init_library (sexp ctx, sexp self, sexp_sint_t n, sexp env, const char* version, sexp_abi_identifier_t abi) {
  sexp_gc_var3(name, tmp, op);
  if (!(sexp_version_compatible(ctx, version, sexp_version)
        && sexp_abi_compatible(ctx, abi, SEXP_ABI_IDENTIFIER)))
    return SEXP_ABI_ERROR;
  sexp_gc_preserve3(ctx, name, tmp, op);
  name = sexp_intern(ctx, "seek/end", 8);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, SEEK_END));
  name = sexp_intern(ctx, "seek/cur", 8);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, SEEK_CUR));
  name = sexp_intern(ctx, "seek/set", 8);
  sexp_env_define(ctx, env, name, tmp=sexp_make_integer(ctx, SEEK_SET));
  op = sexp_define_foreign_param(ctx, env, "peek-u8", 1, (sexp_proc1)sexp_peek_u8_stub, "current-input-port");
  op = sexp_define_foreign_param(ctx, env, "read-u8", 1, (sexp_proc1)sexp_read_u8_stub, "current-input-port");
  op = sexp_define_foreign_param(ctx, env, "write-u8", 2, (sexp_proc1)sexp_write_u8_stub, "current-output-port");
  op = sexp_define_foreign(ctx, env, "utf8->string!", 1, (sexp_proc1)sexp_utf8_3E_string_x_stub);
  op = sexp_define_foreign(ctx, env, "%string->utf8", 1, (sexp_proc1)sexp_25_string_3E_utf8_stub);
  op = sexp_define_foreign_opt(ctx, env, "string-count", 4, (sexp_proc1)sexp_string_count_stub, SEXP_FALSE);
  op = sexp_define_foreign(ctx, env, "get-output-bytevector", 1, (sexp_proc1)sexp_get_output_bytevector_stub);
  op = sexp_define_foreign(ctx, env, "open-output-bytevector", 0, (sexp_proc1)sexp_open_output_bytevector_stub);
  op = sexp_define_foreign(ctx, env, "open-input-bytevector", 1, (sexp_proc1)sexp_open_input_bytevector_stub);
  op = sexp_define_foreign(ctx, env, "%make-custom-output-port", 3, (sexp_proc1)sexp_25_make_custom_output_port_stub);
  op = sexp_define_foreign(ctx, env, "%make-custom-input-port", 3, (sexp_proc1)sexp_25_make_custom_input_port_stub);
  op = sexp_define_foreign(ctx, env, "set-file-position!", 3, (sexp_proc1)sexp_set_file_position_x_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_IPORT);
    sexp_opcode_arg2_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg3_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
  }
  op = sexp_define_foreign(ctx, env, "file-position", 1, (sexp_proc1)sexp_file_position_stub);
  if (sexp_opcodep(op)) {
    sexp_opcode_return_type(op) = sexp_make_fixnum(SEXP_FIXNUM);
    sexp_opcode_arg1_type(op) = sexp_make_fixnum(SEXP_IPORT);
  }
  sexp_gc_release3(ctx);
  return SEXP_VOID;
}

